# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
guest = User.new(first_name: "guest",last_name: "guest",username: "guest",campaign_1_finished: false, campaign_2_finished: false, campaign_3_finished: false)
guest.password = "1"
guest.save
Campaign.create(description: "this is the first campaign")
Storyline.create(header: "Enter",story_body: "this is the body",img_url: "",campaign_id: 1,option_1_id: 2,option_2_id:3)
Storyline.create(header:"Door",story_body: "this is the body",img_url: "",campaign_id: 1,option_1_id: 10,option_2_id: 4)
Storyline.create(header:"Passageway",story_body: "this is the body",img_url: "",campaign_id: 1,option_1_id: 4,option_2_id: 5)
Storyline.create(header:"Hallway",story_body: "this is the body",img_url: "",campaign_id: 1,option_1_id: 11,option_2_id: 6)
Storyline.create(header:"shower",story_body: "this is the body",img_url: "",campaign_id: 1,option_1_id: 6,option_2_id: 7)
Storyline.create(header:"learn",story_body: "this is the body",img_url: "",campaign_id: 1,option_1_id: 12,option_2_id: 8)
Storyline.create(header:"study",story_body: "this is the body",img_url: "",campaign_id: 1,option_1_id: 8,option_2_id: 9)
Storyline.create(header:"almost there",story_body: "this is the body",img_url: "",campaign_id: 1,option_1_id: 13,option_2_id: 14)
Storyline.create(header:"almost survived",story_body: "this is the body",img_url: "",campaign_id: 1,option_1_id: 8,option_2_id: 15)
Storyline.create(header:"dead1",story_body: "this is the body",img_url: "",campaign_id: 1,option_1_id: 0,option_2_id: 0)
Storyline.create(header:"Death2",story_body: "this is the body",img_url: "",campaign_id: 1,option_1_id: 0,option_2_id: 0)
Storyline.create(header:"Death3",story_body: "this is the body",img_url: "",campaign_id: 1,option_1_id: 0,option_2_id: 0)
Storyline.create(header:"Death4",story_body: "this is the body",img_url: "",campaign_id: 1,option_1_id: 0,option_2_id: 0)
Storyline.create(header:"Death5",story_body: "this is the body",img_url: "",campaign_id: 1,option_1_id: 0,option_2_id: 0)
Storyline.create(header:"Win",story_body: "this is the body",img_url: "",campaign_id: 1,option_1_id: 1,option_2_id: 1)

Campaign.create(description: "This is the second campaign")
Storyline.create(header: "Enter2",story_body: "this is the body",img_url: "",campaign_id: 2,option_1_id: 17,option_2_id: 18)
Storyline.create(header: "Door2",story_body: "this is the body",img_url: "",campaign_id: 2,option_1_id: 28, option_2_id: 19)
Storyline.create(header: "Passageway2",story_body: "this is the body",img_url: "",campaign_id: 2,option_1_id: 20,option_2_id: 29)
Storyline.create(header: "Hallway2",story_body: "this is the body",img_url: "",campaign_id: 2,option_1_id: 23,option_2_id: 22)
Storyline.create(header: "shower2",story_body: "this is the body",img_url: "",campaign_id: 2,option_1_id: 19,option_2_id: 21)
Storyline.create(header: "learn2",story_body: "this is the body",img_url: "",campaign_id: 2,option_1_id: 19,option_2_id: 25)
Storyline.create(header: "study2",story_body: "this is the body",img_url: "",campaign_id: 2,option_1_id: 30,option_2_id: 26)
Storyline.create(header: "almost there2",story_body: "this is the body",img_url: "",campaign_id: 2,option_1_id: 27,option_2_id: 24)
Storyline.create(header: "almost survived2",story_body: "this is the body",img_url: "",campaign_id: 2,option_1_id: 30,option_2_id: 26)
Storyline.create(header: "dead2",story_body: "this is the body",img_url: "",campaign_id: 2,option_1_id: 26,option_2_id:30)
Storyline.create(header: "Death2.1",story_body: "this is the body",img_url: "",campaign_id: 2,option_1_id: 0,option_2_id:0)
Storyline.create(header: "Death3.2",story_body: "this is the body",img_url: "",campaign_id: 2,option_1_id: 0,option_2_id:0)
Storyline.create(header: "Death4.1",story_body: "this is the body",img_url: "",campaign_id: 2,option_1_id: 0,option_2_id:0)
Storyline.create(header: "Death5.1",story_body: "this is the body",img_url: "",campaign_id: 2,option_1_id: 0,option_2_id:0)
Storyline.create(header: "win2",story_body: "this is the body",img_url: "",campaign_id: 2,option_1_id: 0,option_2_id:0)

Campaign.create(description: "This is the third campaign")
Storyline.create(header: "Enter2",story_body: "this is the body",img_url: "",campaign_id: 3,option_1_id: 17,option_2_id:18)
Storyline.create(header: "Door2",story_body: "this is the body",img_url: "",campaign_id: 3,option_1_id: 17,option_2_id:18)
Storyline.create(header: "Passageway3",story_body: "this is the body",img_url: "",campaign_id: 3,option_1_id: 17,option_2_id:18)
Storyline.create(header: "Hallway3",story_body: "this is the body",img_url: "",campaign_id: 3,option_1_id: 17,option_2_id:18)
Storyline.create(header: "shower3",story_body: "this is the body",img_url: "",campaign_id: 3,option_1_id: 17,option_2_id:18)
Storyline.create(header: "learn3",story_body: "this is the body",img_url: "",campaign_id: 3,option_1_id: 17,option_2_id:18)
Storyline.create(header: "study3",story_body: "this is the body",img_url: "",campaign_id: 3,option_1_id: 17,option_2_id:18)
Storyline.create(header: "almost there3",story_body: "this is the body",img_url: "",campaign_id: 3,option_1_id: 17,option_2_id:18)
Storyline.create(header: "almost survived3",story_body: "this is the body",img_url: "",campaign_id: 3,option_1_id: 17,option_2_id:18)
Storyline.create(header: "dead3",story_body: "this is the body",img_url: "",campaign_id: 3,option_1_id: 17,option_2_id:18)
Storyline.create(header: "Death2.3",story_body: "this is the body",img_url: "",campaign_id: 3,option_1_id: 17,option_2_id:18)
Storyline.create(header: "Death3.3",story_body: "this is the body",img_url: "",campaign_id: 3,option_1_id: 17,option_2_id:18)
Storyline.create(header: "Death4.3",story_body: "this is the body",img_url: "",campaign_id: 3,option_1_id: 17,option_2_id:18)
Storyline.create(header: "Death5.3",story_body: "this is the body",img_url: "",campaign_id: 3,option_1_id: 17,option_2_id:18)
Storyline.create(header: "win3",story_body: "this is the body",img_url: "",campaign_id: 3,option_1_id: 17,option_2_id:18)
